import Foundation

import SwiftUI

struct Activity: Identifiable{
    var id = UUID()
    var type : String
    var titre: String
    var image : String
    var localisation : String
    var adresse : String
    var nombreAvis : Int
    var etoile : Int
    var description : String
    var longitude : Double
    var latitude : Double
    var addFavorite : Bool = false
    var details : String
    var conditions : String
    
    func favoriteStatus() -> (image: String, color: Color) {
        return addFavorite ? ("heart.fill", .red) : ("heart", .white)
    }
}

var activitiesArray = [
    
    Activity(type: "sport", titre: "Kayak transparent", image: "kayak", localisation: "Marseille (13008)", adresse: "Plages du Prado", nombreAvis: 45, etoile: 4, description: "Le kayak transparent est un nouveau type de canoë kayak, accessible à tous. En location libre ou en balade avec un guide observez la faune et la flore sous marine à bord d’une embarcation entièrement transparente. Vous vivrez cette expérience dans une commune française nommée Le Pradet et située dans le département du Var, en région Provence-Alpes-Côte d'Azur. Cette activité nautique se pratique à l'intérieur du lagon en toute sécurité, et sans forcément vous mouiller.", longitude: 5.38, latitude: 43.26, addFavorite: false, details: "• Visibilité jusqu'à 20 mètres\n• 1 ou 2 place(s)\n• Traité anti-uv", conditions: "• Âge minimum : 5 ans\n• Traité anti-uv\n• Aisance aquatique\n• Maximum poids total : 220kg"),
    
    Activity(type: "sport", titre: "Parapente", image: "parapente", localisation: "Menton (06500)", adresse: "Plage de Carnolès", nombreAvis: 45, etoile: 4, description: "Sport extrême, pratiqué en douceur. Planeur ultraléger et souple, permettant de pratiquer le vol libre. Le parapente est un aéronef composé d'une toile en tissu léger encaissant l'air dans des alvéoles. Les suspentes sont les fils qui relient la voile à la sellette. Elles sont associées aux commandes situées à droite et à gauche du moniteur.", longitude: 7.47, latitude: 43.77, addFavorite: false, details: "• Horaires : les vols de 15 minutes s'effectuent le matin, et ceux de 45 minutes l'après-midi.\n• Reportage photo et vidéo HD, carte SD fournie : 40€ ou 30€ avec votre mini SD.\n• Activité réalisable de mai à octobre", conditions: "• À partir de 5 ans avec autorisation parentale\n• Ne pas présenter de contre-indications de santé\n• Poids max : 100 kg\n• Être équipé de chaussures de sport"),
    
    Activity(type: "sport", titre: "Balade à cheval", image: "equitation", localisation: "Grimaud (83310)", adresse: "Chemin de la Tour", nombreAvis: 45, etoile: 4, description: "Les cheveux au vent, cette balade à cheval sur la plage procure le bien-être au rythme des vagues.", longitude: 6.52, latitude: 43.27, addFavorite: false, details: "• Activité soumise aux conditions météo\n• Durée, au choix, entre 1h et une demi-journée\n• Plusieurs balade différents niveaux", conditions: "• Tenue confortable de saison, chaussures fermées\n• Poids autorisé : maxi 90 kg\n• Autorisation parentale (pour les mineurs)\n• Être équipé de chaussures de sport"),
    
    Activity(type: "solidaire", titre: "Nettoyage actif", image: "benevole1", localisation: "St Raphaël (83700)", adresse: "Plage du Veillat", nombreAvis: 76, etoile: 4, description: "En associant le nettoyage des plages, la sensibilisation aux déchets marins et la promotion du tourisme responsable, les initiatives de développement durable protègent la beauté des côtes et la santé des écosystèmes marins.", longitude: 6.77, latitude: 43.42, addFavorite: true, details: "• L'équipement (paire de gants, sacs poubelles, pinces à main) vous sera fourni.\n• Trier au maximum les déchets (plastique, verre, carton...).\n• Ne pas s'aventurer dans les endroits non sécurisés.", conditions: "• Les enfants doivent être accompagnés d’un adulte\n• Garder vos chaussures lors du nettoyage\n• Utiliser les gants mis à disposition"),
    
    Activity(type: "solidaire", titre: "Dunes et côtes", image: "benevole2", localisation: "Le Grau-du-Roi (30240)", adresse: "Plage de l'Espiguette", nombreAvis: 29, etoile: 3, description: "Ramassez les déchets marins pour préserver le littoral, visant à la fois la protection de l'environnement et la sensibilisation. Les organisateurs sollicitent la participation de volontaires afin de contribuer à la préservation du littoral en ramassant les déchets marins. Une opération avec un double objectif.", longitude: -1.43, latitude: 43.63, addFavorite: true, details: "• Assurance non prise en charge\n• Des gants seront mis à disposition", conditions: "• Ne pas marcher sur la dune\n• Prévoir une tenue adaptée aux conditions météorologiques et une gourde.\n• Les enfants doivent être accompagnés d’un adulte."),
    
    Activity(type: "solidaire", titre: "Plages Nettes", image: "benevole3", localisation: "Marseille (13008)", adresse: "Plage de l'Huveaune", nombreAvis: 43, etoile: 4, description: "La protection des plages est essentielle pour préserver nos écosystèmes marins uniques. A fond sur le développement durable des plages qui est essentiel pour sauvegarder nos écosystèmes côtiers uniques. Prends soin de ton lieu de vacances ! Matériel : Les sacs à déchets seront fournis sur place.", longitude: 5.40, latitude: 43.30, addFavorite: true, details: "• Pensez à vous munir d’une paire de gants type gants de jardinage\n• Trier au maximum les déchets", conditions: "• Ne pas toucher les déchets dangereux (coupants, piquants) ou suspects (fûts, bouteilles de produits chimiques, seringues...).\n• Attention aux hauteurs de berges parfois glissantes.\n• Respecter les panneaux jaunes de signalisation pour votre sécurité\n• Si vous constatez une situation qui met en danger des personnes, composez le 18 ou le 112 pour les téléphones mobiles."),
    
    Activity(type: "solidaire", titre: "Bonne pêche", image: "benevole4", localisation: "Port-de-Bouc (13110)", adresse: "Port-de-Bouc", nombreAvis: 6, etoile: 5, description: "Ré-équilibrez l'écosystème et approfondissez vos connaissances en pisciculture. La pêche durable respecte davantage la biodiversité et les écosystèmes marins que la pêche conventionnelle grâce à des critères et des techniques de pêche stricts. Labels, techniques et impact sur la biodiversité, venez découvrir la pêche durable encadrée par des passionnés.", longitude: 4.98, latitude: 43.40, addFavorite: true, details: "• Saison hivernale : pêche entre 11h00 et 14h00", conditions: "• Respecter la taille des poissons à pêcher\n• Ne pas déplacer ou soulever une pierre, ou la replacer au même endroit lorsque l'on pratique la pêche à pied.\n• Limiter au maximum les prises accidentelles\n• Ne pas cibler les espèces les plus menacées."),
    
    Activity(type: "art", titre: "Peinture galet", image: "art1", localisation: "Martigues (13500) ", adresse: "36 rue de la plage", nombreAvis: 32, etoile: 4, description: "L’utilisation de galets comme supports de création ne date pas d’hier, bien au contraire. Au cours de l’Histoire, de nombreuses civilisations ont eu recours aux galets, ou aux pierres en général, en tant qu’objets utilitaires. Néanmoins, le concept de la peinture sur galet est bien plus récent, puisqu’il repose sur une idée britannique appelée « Love on the rocks » (« L’amour sur les rochers »), qui consiste à peindre des galets pour ensuite les cacher, afin que d’autres aient le plaisir de les trouver, pour les recacher ailleurs.", longitude: 5.01, latitude: 43.39, addFavorite: false, details: "• 10 Personne(s) maxi\n• De 13:00 à 15:30\n• Tout le matériel nécessaire est mis à votre disposition.\n• Grand choix de peinture", conditions: "• Atelier intergénérationnel de 7 à 99 ans\n• Aucun prérequis n'est nécessaire"),
    
    Activity(type: "art", titre: "Atelier macramé", image: "art2", localisation: "Hyères (83400) ", adresse: "12 rue du château", nombreAvis: 32, etoile: 4, description: "Grande tendance des années 70, le macramé revient à la mode dans un style bohème chic. Venez découvrir les nœuds plats, les nœuds ondulés… pendant cet atelier de 3 heures. Le macramé est une technique de point noué permettant de réaliser de la décoration pour votre intérieur, accessoires, bijoux… Venez pimper votre intérieur avec un jardin suspendu, deux modèles à choisir.Venez découvrir les différents types de nœuds repartez avec votre création !", longitude: 6.13, latitude: 43.12, addFavorite: false, details: "• Matériels mis à disposition et fournitures inclus.\n• Durée : 3 heures\n• Cordes de coton recyclé \n• Boissons et pâtisseries maison vous seront proposées à chaque atelier. \n• Vous repartirez avec votre création terminée à la fin de l’atelier.", conditions: "• Avoir au moins 7 ans. \nLes enfants mineurs doivent être accompagnés d'un adulte.\n• Aucun prérequis n'est nécessaire"),
    
    Activity(type: "art", titre: "Atelier céramique", image: "art3", localisation: "Pontes (13540) ", adresse: "Chemin de Maliverny", nombreAvis: 32, etoile: 4, description: "Laissez libre cours à votre créativité et vivez une expérience artistique mémorable entre amis ou en duo mère-fille parr exemple ! Profitez d'un moment de créativité et de complicité, immergés dans un environnement verdoyant dans la campagne aixoise !", longitude: 5.40, latitude: 43.58, addFavorite: false, details: "• Jusqu'à 4 personnes\n• Durée : 2 heures 30 minutes\n• Apprentissage des gestes de base \n• Prix / Personne : 60€\n• À la fin de l’initiation vous garderez 3 pièces et choisirez votre couleur d’émail.", conditions: "• À partir de 16 ans\n• Annulation gratuite jusqu'à 7 jours avant la date de l'activité."),
    
    Activity(type: "nature", titre: "Nurserie de poissons", image: "fauneetflore4", localisation: " Toulon (83000)", adresse: "Quai océanographique de l’Ifremer", nombreAvis: 43, etoile: 4, description: "Contre la paroi du quai, des plongeurs font descendre dans les profondeurs trois murs végétaux de roselières de 150 mètres carrés. Ces herbiers artificiels reproduisent les habitats des espèces marines locales en imitant les caractéristiques des herbiers de posidonie méditerranéens.", longitude: 5.93, latitude: 43.12, addFavorite: false, details: "• Visite autonome du port avec les paneaux d'explications disposés à chaque point stratégique.\n• Jeu interactif disponible en scannant les QRCodes des panneaux.", conditions: "• Ne pas s'approcher trop prêt du bord des quais."),
    
    Activity(type: "nature", titre: "Sortie ornithologique", image: "fauneetflore1", localisation: "Istres (13800)", adresse: "Etang de l'Olivier ", nombreAvis: 12, etoile: 4, description: "La station LPO (Ligue de Protection des Oiseaux) organise des expositions, des excursions commentées aux Sept-Îles (plus grande réserve française d’oiseaux marins) et des sorties nature : oiseaux, plantes du littoral, sorties à marée basse... La station LPO de l’Île-Grande a été labellisée « Maison Nature » par le conseil départemental.", longitude: 4.98, latitude: 43.52, addFavorite: false, details: "• Ouverture : Mai : week-ends, jours fériés et ponts de 14h à 18h\nJuin, septembre et vacances scolaires (toutes zones) : tous les jours de 14h à 18h. \nJuillet et août : 10h à 13h et de 14h30 à 19h, fermé le samedi matin et le dimanche matin.\nVacances de Noël de 14h à 17h.", conditions: "• Le bruit et la présence d’aéronefs (y compris de drones) peuvent perturber la faune tant dans l’eau que sur terre.\n• Arrivez à bonne distance, avancez lentement tout en observant leurs comportements. Des cris d’alarmes vous feront comprendre qu’il est préférable de ne plus avancer.\n• D'autres explications vous serons fournies par notre équipe."),
    
    Activity(type: "nature", titre: "La flore des dunes", image: "fauneetflore2", localisation: "Le Grau-du-Roi (30240)", adresse: "Plage de l'Espiguette", nombreAvis: 27, etoile: 5, description: "Venez découvrir le fonctionnement des dunes et les plantes qui y sont inféodées. Nous emprunterons le platelage du sentier du littoral. Le lieu de rendez-vous est au niveau de la page de l'Espiguette. 15€, Réservation obligatoire à l'avance en priorité par SMS au 07.80.50.39.25 ou mail. Les sorties s'effectuent à partir de 4 participants.", longitude: -1.42, latitude: 43.6, addFavorite: false, details: "• Tarif 7 € par personne\n• Thèmes abordés : Développement durable, Fleurs et Plantes, Nature...", conditions: "• Au minimum être un groupe composé de 4 personnes\n• Réservation obligatoire\n• Merci de ne ceuillir aucune plantes ou fleurs sur votre chemin."),
    
    Activity(type: "nature", titre: "Algues en cuisine", image: "fauneetflore3", localisation: " Nice (06100)", adresse: "32 Cour Saleya", nombreAvis: 11, etoile: 5, description: "Venez découvrir l’univers de ces végétaux et leurs propriétés. Une animation comprenant une découverte des algues, un atelier de création de cocktail pétillant à base de billes d’algues aromatisées.", longitude: 7.25, latitude: 43.70, addFavorite: false, details: "• Tarif : 14€\n• Durée : 2h30\n• Réservation à l'Office de Tourisme", conditions: "• Langue parlée : français\n• Ateliers réalisés tous les samedis matins en juin, juillet et août.\n• Âge minmum : 10 ans"),
    
    Activity(type: "culture", titre: "Riviera & Merveilles", image: "culture2", localisation: "Menton (06500)", adresse: "8 Avenue de l'Europe", nombreAvis: 13, etoile: 3, description: "Partez à la découverte de Menton et du Pays Mentonnais à travers une série de défis ludiques ! A l'aide d'un sac à dos rempli d'accessoires d'exploration et d'un chatbot, résolvez l'énigme associée à chaque quartier. Votre aventure commence après avoir obtenu un sac dans l'Office de Tourisme de Menton. Accessoire et jeu réalisés de manière éco responsable.", longitude: 7.5, latitude: 43.78, addFavorite: false, details: "• 1 sac à dos \"Explore Bag\" pour un groupe de 1 à 4 personnes.\n• Disponible toute l'année : à la journée ou sur plusieurs jours.\n• Durée location maximale du sac à dos : 1 semaine", conditions: "• Une caution de 50 € par chèque, espèces ou chèque-vacances sera demandée au moment de la location du sac à dos.\n• Langues de traduction disponibles : français, anglais, italien, espagnol."),
    
    Activity(type: "culture", titre: "Phare Cassidaigne", image: "culture1", localisation: "Cassis (33123)", adresse: "Phare Cassidaigne", nombreAvis: 43, etoile: 5, description: "Soumis aux vents et marées, le Phare Cassidaigne a été construit en 1859. Il fait partie des monuments incontournables de la région Provence-Alpes-Côté-d'Azur. Après avoir gravi les 365 marches, le balcon au sommet du phare offre une vue à couper le souffle.", longitude: 5.62, latitude: 43.16, addFavorite: false, details: "• Après une balade en bateau d’environ 45 minutes, les gardiens vous accueillent sur le phare.\n• Navettes payantes : 22€ par personne en basse-saison et 34€ par personne en haute-saison.\n• Au départ de Cassis ou La Ciotat, vous embarquez pour une sortie d’environ 4h.", conditions: "• La visite est contre-indiquée aux visiteurs présentant des difficultés à marcher, ou souffrant de troubles cardio-respiratoires ou autres contre-indications médicales.\n• Réservation directement en ligne ou en téléphonant aux compagnies de croisières.")
]
